# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dbMaxC <- function(x, block_size) {
    .Call(`_maxbootR_dbMaxC`, x, block_size)
}

seqC <- function(a, b) {
    .Call(`_maxbootR_seqC`, a, b)
}

slidMaxC <- function(xx, r) {
    .Call(`_maxbootR_slidMaxC`, xx, r)
}

repC <- function(val, times) {
    .Call(`_maxbootR_repC`, val, times)
}

kMaxTrC <- function(sample, r, k) {
    .Call(`_maxbootR_kMaxTrC`, sample, r, k)
}

convert_to_doubles <- function(char_vec) {
    .Call(`_maxbootR_convert_to_doubles`, char_vec)
}

meanCTabVec <- function(xx) {
    .Call(`_maxbootR_meanCTabVec`, xx)
}

varCTabVec <- function(xx) {
    .Call(`_maxbootR_varCTabVec`, xx)
}

neg_log_likelihood_gev <- function(theta, xx) {
    .Call(`_maxbootR_neg_log_likelihood_gev`, theta, xx)
}

neg_log_likelihood_gev_univ <- function(theta, x) {
    .Call(`_maxbootR_neg_log_likelihood_gev_univ`, theta, x)
}

neg_log_likelihood_gev_lvec <- function(theta, xx) {
    .Call(`_maxbootR_neg_log_likelihood_gev_lvec`, theta, xx)
}

